In [1]:
import pandas as pd
import numpy as np

from sklearn.svm import SVC
#from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from sklearn.preprocessing import LabelEncoder

In [2]:
%store -r featuresdf_test_EMODB
%store -r featuresdf_train_EMODB

In [3]:
X_test = np.array(featuresdf_test_EMODB.feature.tolist())
y_test = np.array(featuresdf_test_EMODB.class_label.tolist())

le = LabelEncoder()
y_test = le.fit_transform(y_test)

X_train = np.array(featuresdf_train_EMODB.feature.tolist())
y_train = np.array(featuresdf_train_EMODB.class_label.tolist())

y_train = le.fit_transform(y_train)

In [5]:
%store -r  featuresdf_test_emovo
%store -r  featuresdf_train_emovo

In [6]:
# Convert features and corresponding classification labels into numpy arrays
X_test = np.array(featuresdf_test_emovo.feature.tolist())
y_test = np.array(featuresdf_test_emovo.class_label.tolist())

le = LabelEncoder()
y_test = le.fit_transform(y_test)

X_train = np.array(featuresdf_train_emovo.feature.tolist())
y_train = np.array(featuresdf_train_emovo.class_label.tolist())

y_train = le.fit_transform(y_train)

In [11]:
"""
#usar con "from sklearn.svm import LinearSVC" descomentando arriba
#svclassifier = LinearSVC(random_state=0, tol=1e-5,multi_class='crammer_singer',max_iter=100000,dual = True)
"""

#svclassifier = SVC(kernel='poly', degree=3)
#svclassifier = SVC(kernel='sigmoid')
#svclassifier = SVC(kernel='precomputed')
#svclassifier = SVC(kernel='rbf')
#svclassifier = SVC(kernel='linear')


for kernel in ('linear', 'rbf', 'poly', 'sigmoid'):
    svclassifier = SVC(kernel=kernel, gamma=1, degree=3)
    svclassifier.fit(X_train, y_train)
    print('{:.2f}'.format(svclassifier.score(X_test,y_test)),'(',kernel,')')
    
for kernel in ('linear', 'rbf', 'poly', 'sigmoid'):
    svclassifier = SVC(kernel=kernel, gamma=1, degree=3)
    svclassifier.fit(X_train, y_train)
    print(kernel)
    print('Accuracy of SVM classifier on training set : {:.2f}'.format(svclassifier.score(X_train,y_train)))
    print('Accuracy of SVM classifier on test set : {:.2f}'.format(svclassifier.score(X_test,y_test)))
    pred = svclassifier.predict(X_test)
    print(confusion_matrix(y_test,pred))
    print(classification_report(y_test,pred))
    
    
    


0.48 ( linear )
0.69 ( rbf )
0.66 ( poly )
0.14 ( sigmoid )
linear
Accuracy of SVM classifier on training set : 0.74
Accuracy of SVM classifier on test set : 0.48
[[12  2  0  9  1  1  0]
 [ 3 14  2  3  1  2  0]
 [ 2  5  7  6  3  1  1]
 [ 6  3  0 15  0  0  1]
 [ 3  4  3  5  8  1  1]
 [ 3  1  0  7  0 14  0]
 [ 2  2  3  2  2  0 14]]
              precision    recall  f1-score   support

           0       0.39      0.48      0.43        25
           1       0.45      0.56      0.50        25
           2       0.47      0.28      0.35        25
           3       0.32      0.60      0.42        25
           4       0.53      0.32      0.40        25
           5       0.74      0.56      0.64        25
           6       0.82      0.56      0.67        25

    accuracy                           0.48       175
   macro avg       0.53      0.48      0.49       175
weighted avg       0.53      0.48      0.49       175

rbf
Accuracy of SVM classifier on training set : 0.99
Accuracy of SVM c

In [115]:
%store -r featuresdf_EMODB

In [8]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split 

# Convert features and corresponding classification labels into numpy arrays
X = np.array(featuresdf_EMODB.feature.tolist())
y = np.array(featuresdf_EMODB.class_label.tolist())

# Encode the classification labels
le = LabelEncoder()
yy = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, yy, test_size=0.3, random_state = 42)

In [109]:
%store -r  featuresdf_emovo

In [138]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split 

# Convert features and corresponding classification labels into numpy arrays
X = np.array(featuresdf_emovo.feature.tolist())
y = np.array(featuresdf_emovo.class_label.tolist())

# Encode the classification labels
le = LabelEncoder()
yy = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, yy, test_size=0.4, random_state = 42)

In [123]:
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[ 1.05350886 -1.42402972  1.88759231 ... -0.05544014  1.94579621
  -0.6733853 ]
 [ 0.78410446  0.77594841  0.12109369 ...  0.11870067  1.33393016
   0.52708638]
 [ 0.43657027  0.50739396  0.64315671 ... -0.02385506  0.82592542
   0.45815247]
 ...
 [ 1.11396272 -0.11072533  0.58440554 ...  0.29411815  1.07472926
  -0.13666378]
 [ 1.24599186  0.41924242 -0.01027561 ...  0.12321439 -0.40593105
   0.93963247]
 [ 1.09291176 -0.08123305  0.63841025 ...  0.23636797  0.26532027
   1.08654712]]
[[ 0.9175803  -0.49139902  0.64278311 ...  0.36489207  0.24398483
  -0.04402874]
 [ 0.72725537  0.28647801 -0.01189145 ...  0.1644106   0.95037322
   0.60078656]
 [ 1.13386822 -0.50428006  0.59759616 ...  0.39989914  0.72464263
   0.77688845]
 ...
 [ 0.53724076 -0.58692115  1.23401442 ... -0.10976449  0.18816868
  -0.50186961]
 [ 0.85527155 -0.14969513  0.06638676 ...  0.30659506  0.97545801
   0.56461936]
 [ 0.532708   -0.02528799  0.36805879 ... -0.03602712  0.32346575
   0.41946789]]
[5 3 0 1 0 3 4 5