In [1]:
import pandas as pd
import numpy as np

from sklearn.svm import SVC
#from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

from sklearn.preprocessing import LabelEncoder

In [6]:
%store -r featuresdf_test_EMODB
%store -r featuresdf_train_EMODB

In [10]:
X_test = np.array(featuresdf_test_EMODB.feature.tolist())
y_test = np.array(featuresdf_test_EMODB.class_label.tolist())

le = LabelEncoder()
y_test = le.fit_transform(y_test)

X_train = np.array(featuresdf_train_EMODB.feature.tolist())
y_train = np.array(featuresdf_train_EMODB.class_label.tolist())

#y_train = le.fit_transform(y_train)

In [11]:
y_train

array(['A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'E disgusto',
       'E disgusto', 'E disgusto', 'E disgusto', 'E disgusto',
       'E disgusto', 'E disgusto', 'E disgusto', 'E disgusto',
       'E disgusto', 'E disgusto', 'E disgusto', 'E dis

In [8]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,

In [12]:
%store -r  featuresdf_test_emovo
%store -r  featuresdf_train_emovo

In [15]:
# Convert features and corresponding classification labels into numpy arrays
X_test = np.array(featuresdf_test_emovo.feature.tolist())
y_test = np.array(featuresdf_test_emovo.class_label.tolist())

le = LabelEncoder()
y_test = le.fit_transform(y_test)

X_train = np.array(featuresdf_train_emovo.feature.tolist())
y_train = np.array(featuresdf_train_emovo.class_label.tolist())

#y_train = le.fit_transform(y_train)

In [16]:
y_train

array(['A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'A angustia', 'A angustia',
       'A angustia', 'A angustia', 'E disgusto', 'E disgusto',
       'E disgusto', 'E disgusto', 'E disgusto', 'E dis

In [14]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5,

In [8]:
for n in range(1,6,2):
    #print('n_neighbors =', n)
    n_neighbors = n

    knn = KNeighborsClassifier(n_neighbors, metric = 'minkowski', p = 2)
    knn.fit(X_train,y_train)
    print('{:.2f}'.format(knn.score(X_test,y_test)),'(',n,')')
   
for n in range(1,6,2):
    n_neighbors = n
    knn = KNeighborsClassifier(n_neighbors, metric = 'minkowski', p = 2)
    knn.fit(X_train,y_train)
    print('Accuracy of KNN classifier on training set : {:.2f}'.format(knn.score(X_train,y_train)))
    print('Accuracy of KNN classifier on test set : {:.2f}'.format(knn.score(X_test,y_test)))

    pred = knn.predict(X_test)
    conf_mat = confusion_matrix(y_test,pred)
    report = classification_report(y_test,pred)
    print(conf_mat)
    print(report)


0.63 ( 1 )
0.65 ( 3 )
0.63 ( 5 )
Accuracy of KNN classifier on training set : 1.00
Accuracy of KNN classifier on test set : 0.63
[[18  2  2  1  0  2  0]
 [ 3 18  0  2  2  0  0]
 [ 1  1  9  8  2  0  4]
 [ 1  3  2 17  1  0  1]
 [ 0  2  3  2 17  0  1]
 [ 3  1  0  2  2 16  1]
 [ 2  3  4  1  0  0 15]]
              precision    recall  f1-score   support

           0       0.64      0.72      0.68        25
           1       0.60      0.72      0.65        25
           2       0.45      0.36      0.40        25
           3       0.52      0.68      0.59        25
           4       0.71      0.68      0.69        25
           5       0.89      0.64      0.74        25
           6       0.68      0.60      0.64        25

    accuracy                           0.63       175
   macro avg       0.64      0.63      0.63       175
weighted avg       0.64      0.63      0.63       175

Accuracy of KNN classifier on training set : 0.89
Accuracy of KNN classifier on test set : 0.65
[[18  2  

In [14]:
%store -r featuresdf_EMODB

In [16]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split 

# Convert features and corresponding classification labels into numpy arrays
X = np.array(featuresdf_EMODB.feature.tolist())
y = np.array(featuresdf_EMODB.class_label.tolist())

# Encode the classification labels
le = LabelEncoder()
yy = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, yy, test_size=0.4, random_state = 42)

In [31]:
%store -r  featuresdf_emovo

In [32]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split 

# Convert features and corresponding classification labels into numpy arrays
X = np.array(featuresdf_emovo.feature.tolist())
y = np.array(featuresdf_emovo.class_label.tolist())

# Encode the classification labels
le = LabelEncoder()
yy = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, yy, test_size=0.4, random_state = 42)